[project]
name = "ps-client"
version = "0.6.1"
description = "client to read configuration from AWS Parameter Store"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.36",
]
authors = [
    { name = "Krishnan M", email = "krishnan.mani@ashmus.ox.ac.uk" }
]
keywords = ["AWS", "parameter-store", "config", "secrets"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "boto3-stubs>=1.42.61",
    "moto[ssm]>=5.1.20",
    "pytest>=9.0.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ps_client*"]
